# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/user_constrains.xdc

# IP: C:/Users/David/Desktop/KeyGen/KeyGen.ip/mem_g/mem_g.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_g || ORIG_REF_NAME==mem_g} -quiet] -quiet

# IP: C:/Users/David/Desktop/KeyGen/KeyGen.ip/mem_h/mem_h.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_h || ORIG_REF_NAME==mem_h} -quiet] -quiet
