# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/David/Desktop/KeyGen-3/KeyGen.ip/mem_h/mem_h.xci
# IP: The module: 'mem_h' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/David/Desktop/KeyGen-3/KeyGen.ip/mem_h/mem_h_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_h'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/David/Desktop/KeyGen-3/KeyGen.ip/mem_h/mem_h.xci
# IP: The module: 'mem_h' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/David/Desktop/KeyGen-3/KeyGen.ip/mem_h/mem_h_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_h'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
