# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/David/Desktop/KeyGen-2/KeyGen.ip/fifo_rng/fifo_rng.xci
# IP: The module: 'fifo_rng' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/David/Desktop/KeyGen-2/KeyGen.ip/fifo_rng/fifo_rng.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_rng'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/David/Desktop/KeyGen-2/KeyGen.ip/fifo_rng/fifo_rng_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_rng'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/David/Desktop/KeyGen-2/KeyGen.ip/fifo_rng/fifo_rng.xci
# IP: The module: 'fifo_rng' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/David/Desktop/KeyGen-2/KeyGen.ip/fifo_rng/fifo_rng.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_rng'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/David/Desktop/KeyGen-2/KeyGen.ip/fifo_rng/fifo_rng_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_rng'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
