######################################################################
#
# File name : BIKE_1_top_tb_compile.do
# Created on: Tue Mar 26 11:26:28 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.5\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../KeyGen.ip/mul_64bit/mul_64bit/sim/mul_64bit.vhd" \

F:\\modelsim64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../KeyGen.ip/fifo_rng/sim/fifo_rng.v" \
"../../../../src/core_ctrl.v" \
"../../../../src/g_ctrl.v" \
"../../../../src/prng_lcg.v" \
"../../../../src/prng_lcg_tb.v" \
"../../../../src/BIKE_1_top.v" \
"../../../../src/h_ctrl.v" \
"../../../../src/mul_ctrl.v" \
"../../../../KeyGen.ip/mem_g/sim/mem_g.v" \
"../../../../KeyGen.ip/mem_h/sim/mem_h.v" \
"../../../../src/BIKE_1_top_tb.v" \

# compile glbl module
F:\\modelsim64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

