######################################################################
#
# File name : prng_lcg_tb_wave.do
# Created on: Wed Feb 20 20:12:51 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
