######################################################################
#
# File name : BIKE_2_top_tb_wave.do
# Created on: Fri Mar 29 10:22:59 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
