######################################################################
#
# File name : BIKE_1_top_tb_wave.do
# Created on: Tue Mar 05 10:37:54 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
