######################################################################
#
# File name : prng_lcg_tb.udo
# Created on: Wed Feb 20 20:12:52 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
