######################################################################
#
# File name : prng_lcg_tb_compile.do
# Created on: Mon Feb 25 20:16:26 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.5\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../KeyGen.ip/mul_64bit/mul_64bit/sim/mul_64bit.vhd" \

F:\\modelsim64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../src/prng_lcg.v" \
"../../../../src/prng_lcg_tb.v" \

# compile glbl module
F:\\modelsim64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

