######################################################################
#
# File name : BIKE_2_top_tb_wave.do
# Created on: Tue Apr 02 11:02:24 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
