######################################################################
#
# File name : blk_mul_tb_wave.do
# Created on: Sun Apr 07 12:32:58 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
