# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/.Xil/Vivado-39688-David-NTU-Desktop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7s50csga324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      F:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      F:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog {
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/.Xil/Vivado-39688-David-NTU-Desktop/realtime/mem_g_stub.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/.Xil/Vivado-39688-David-NTU-Desktop/realtime/mem_h_stub.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/.Xil/Vivado-39688-David-NTU-Desktop/realtime/mul_64bit_stub.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/.Xil/Vivado-39688-David-NTU-Desktop/realtime/fifo_rng_stub.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/core_ctrl.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/g_ctrl.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/prng_lcg.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/prng_lcg_tb.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/mul_ctrl.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/BIKE_2_top.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/BIKE_2_top_tb.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/h0_ctrl.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/h1_ctrl.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/sparse2dense.v}
      {C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/src/blk_mul.v}
    }
      rt::read_vhdl -lib xpm F:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top BIKE_2_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/David/Desktop/BIKE KeyGen/KeyGen-2/.Xil/Vivado-39688-David-NTU-Desktop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
